### ISSUE TITLE
environment name output name is prefixed with undefined

### ISSUE THREAD

**Issue by kayleejacques** [antifree/json-to-variables#8]
After upgrading the action to latest `1.1.1`,  the ENV outputs appears to be prefixed with `undefined` regardless of whether `prefix` argument is specified or not. 

Code snippet
```
- name: Read Testcase Count
        uses: antifree/json-to-variables@v1.1.1
        with:
          filename: 'xxxxxxxx/history-trend.json'
          prefix: test
```
The env output is being used in a slack action job like this which returned `null` result
```
{
  "type": "mrkdwn",
  "text": "*Passed*\n${{ env.test_0_data_passed }}"
},
```

debug logs snippet 
```
##[debug]Loading inputs
##[debug]Loading env
Run antifree/json-to-variables@v1.1.1
Processing file: xxxxx/history-trend.json
SET ENV 'testundefined_0_buildOrder' = 630
SET ENV 'testundefined_0_reportUrl' = https://xxxxx/630/
SET ENV 'testundefined_0_reportName' = Allure Report with history
SET ENV 'testundefined_0_data_failed' = 1
SET ENV 'testundefined_0_data_broken' = 0
SET ENV 'testundefined_0_data_skipped' = 6
```

Even though it shows `SET ENV 'testundefined_'` , the final ENV is actually something as below
```
  env:
    undefined_0_buildOrder: 630
    undefined_0_reportUrl: https://xxxxxxxxxx/630/
    undefined_0_reportName: Allure Report with history
    undefined_0_data_failed: 1
    undefined_0_data_broken: 0
    undefined_0_data_skipped: 6
    undefined_0_data_passed: 20
    undefined_0_data_unknown: 0
```

It might have something to do when prefix was made optional from this https://github.com/antifree/json-to-variables/pull/5 ? 
A suggestion is much appreciated
